WaterProject/Models/Basket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaterProject.Models
{
    public class Basket
    {
        public List<BasketLineItem> Items { get; set; } = new List<BasketLineItem>();

        public void AddItem(Books book, int qty)
        {
            BasketLineItem line = Items
                .Where(p => p.Book.BookId == book.BookId)
                .FirstOrDefault();

            if (line == null)
            {
                Items.Add(new BasketLineItem
                {
                    Book = book,
                    Quantity = qty
                });
            }
            else
            {
                line.Quantity += qty;
            }
        }
        public double CalculateTotal()
        {
            double sum = Items.Sum(x => x.Quantity * x.Book.Price);
            return sum;
        }
    }

    public class BasketLineItem
    {
        public int LineId { get; set; }
        public Books Book { get; set; }
        public int Quantity { get; set; }

    }
}

WaterProject/Models/Books.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Abstractions;


// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace WaterProject.Models
{
    public partial class Books
    {
        [Key]
        [Required]
        public long BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Isbn { get; set; }
        public string Classification { get; set; }
        public string Category { get; set; }
        public int PageCount { get; set; }
        public double Price { get; set; }
    }
}

WaterProject/Models/BookstoreContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace WaterProject.Models
{
    public class BookstoreContext : DbContext
    {
        public BookstoreContext()
        {
        }

        public BookstoreContext(DbContextOptions<BookstoreContext> options)
            : base(options)
        {
        }

        public DbSet<Books> Books { get; set; }


    }
}

WaterProject/Models/EFWaterProjectRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaterProject.Models
{
    public class EFWaterProjectRepository : IWaterProjectRepository
    {
        private BookstoreContext context { get; set; }
        public EFWaterProjectRepository(BookstoreContext temp)
        {
            context = temp;

        }
        public IQueryable<Books> Books => context.Books;

    }
}

WaterProject/Models/ErrorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaterProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WaterProject/Models/IWaterProjectRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaterProject.Models
{
    public interface IWaterProjectRepository
    {
        IQueryable<Books> Books { get; }
    }
}

WaterProject/Models/ViewModels/PageInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaterProject.Models.ViewModels
{
    public class PageInfo
    {
        public int TotalNumProjects { get; set; }
        public int ProjectsPerPage { get; set; }
        public int CurrentPage { get; set; }
        //Figure out how many pages we need
        public int TotalPages => (int)Math.Ceiling((double)TotalNumProjects / ProjectsPerPage);
    }
}

WaterProject/Models/ViewModels/ProjectsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaterProject.Models.ViewModels
{
    public class ProjectsViewModel
    {
        public IQueryable<Books> Books { get; set; }
        public PageInfo PageInfo { get; set; }
    }
}

WaterProject/Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WaterProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaterProject.Components
{
    public class TypesViewComponent: ViewComponent
    {
        private IWaterProjectRepository repo { get; set; }

        public TypesViewComponent (IWaterProjectRepository temp)
        {
            repo = temp;
        }
        public  IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["projectHi"];
            var types = repo.Books.Select(x => x.Category).Distinct().OrderBy(x => x);

            return View(types);
        }
    }
}

WaterProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WaterProject.Models;
using System.Diagnostics;
using WaterProject.Models.ViewModels;

namespace WaterProject.Controllers
{
    public class HomeController : Controller
    {

        private IWaterProjectRepository repo;

        public HomeController(IWaterProjectRepository temp)
        {
            repo = temp;
        }
        public IActionResult Index(string projectHi, int pageNum = 1)
        {
            int pageSize = 10;
            var x = new ProjectsViewModel
            {
                Books = repo.Books.Where(p => p.Category == projectHi || projectHi == null).OrderBy(p => p.Title).Skip((pageNum - 1) * pageSize).Take(pageSize),
                PageInfo = new PageInfo
                {
                    TotalNumProjects = (projectHi == null ?
                    repo.Books.Count() :
                    repo.Books.Where(x => x.Category == projectHi).Count()),
                    ProjectsPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };

            return View(x);

        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WaterProject/Pages/Donate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WaterProject.Infrastructure;
using WaterProject.Models;

namespace WaterProject.Pages
{
    public class DonateModel : PageModel
    {
        private IWaterProjectRepository repo { get; set; }
        public DonateModel(IWaterProjectRepository temp)
        {
            repo = temp;
        }

        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
        }
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Books b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
            basket.AddItem(b, 1);
            HttpContext.Session.SetJson("basket", basket);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

WaterProject/Pages/Donate.cshtml
@page
@model WaterProject.Pages.DonateModel
@{
}

<h2> Your Basket</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th> Item</th>
            <th> Quantity</th>
            <th> Cost</th>
            <th> Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@i.Book.Price</td>
                <td>@(i.Quantity*i.Book.Price)</td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:  </td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>

WaterProject/Pages/_DonateLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        BOOK Project
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>

WaterProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}
@model ProjectsViewModel


@foreach (Books b in Model.Books)
{
    <partial name="ProjectSummary" model="b"/>
}

<!-- Paginations-->
<div page-model="@Model.PageInfo" page-action="Index" page-classes-enabled="true"
     page-class="btn" page-class-normal="btn-outline-dark"
     page-class-selected="btn-primary" class="btn-group pull-right m-1">
</div>

WaterProject/Views/Shared/Components/Types/Default.cshtml
@{
}
@model IEnumerable<string>
<!-- Partal view-->
<div class="d-grid gap-3 ">
    <a asp-controller="Home" asp-action="Index" asp-route-projectHi="" asp-route-pageNum="" class="btn btn-outline-secondary"> Home</a>
    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-projectHi="@t" asp-route-pageNum="1" class="btn @( ViewBag.SelectedType == t ? "btn-primary":"btn-outline-secondary")">@t</a>
    }
</div>
<br />
<!-- Popover-->
<button type="button" class="btn btn-lg btn-dark" data-toggle="popover" title="Progress bar" data-content="This is the overall progress of the remake of the Amazon website! Almost there!">Click to learn more about this!</button>
<br />
<br />
<!-- Progress bar-->
<div class="progress">
    <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
</div>

WaterProject/Views/Shared/ProjectSummary.cshtml
@{
}
@model Books

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h3>@Model.Title</h3>
        <span class="badge badge-pill badge-primary bg-gradient" style="float:right">
            <span> Price: @Model.Price</span>
        </span>
        <ul class="card-text p">
            <li>
                Author: @Model.Author
            </li>

            <li> Publisher: @Model.Publisher</li>
            <li> ISBN: @Model.Isbn</li>
            <li> Classification: @Model.Classification</li>
            <li> Category: @Model.Category</li>
            <li> PageCount: @Model.PageCount</li>
        </ul>
    </div>
</div>
<br />
<form method="post" asp-page="/Donate">

    <input type="hidden" asp-for="@Model.BookId" />
    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
    <span class="card-text">
        <button type="submit" class="btn btn-success float-right"> Buy </button>
    </span>
</form>

WaterProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission 9 Faline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Book STORE</span>
    </div>
    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">

            @RenderBody()

        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2023 - Mission9_Faline - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>